version: '3'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    env_file:
      - .env

  mongo:
    image: mongo:5
    restart: always
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
